### ISSUE TITLE
Use Selenium html library for tests

### ISSUE THREAD

**Issue by johndharrison** [MangoTheCat/webdriver#23]
Hi Gabor,

Selenium have a large number of HTML pages for testing. You can access them at:

```
svn checkout https://github.com/SeleniumHQ/selenium/trunk/common/src/web

```

May be useful for tests.

**Comment by gaborcsardi** [comment]
There is indeed a lot of pages there. Do they also have some automated tests against them? Or how are they using them?

**Comment by johndharrison** [comment]
They have automated tests against them. For example the python test scripts are at:

https://github.com/SeleniumHQ/selenium/tree/master/py/test/selenium/webdriver/common

**Comment by gaborcsardi** [comment]
I see. TBH I was hoping for tests in some declarative format that I could just use to generate my own tests. 

Still, these will be useful for me to see how things are done. :)
