### ISSUE TITLE
Why are update operations so slow on windows?

### ISSUE THREAD

**Issue by gaborcsardi** [MangoTheCat/webdriver#27]
Came up when @daattali was experimenting with `shinytest`.

**Comment by daattali** [comment]
I just did some very quick n dirty benchmarking using microbenchmark (Windows 7)

```
> microbenchmark::microbenchmark(app$find_element("#num"), app$find_widget("num"), w$get_value(), w$set_value("1"), times = 10)
Unit: milliseconds
                     expr       min        lq      mean    median        uq       max neval
 app$find_element("#num")  233.9009  234.5633  239.3968  236.7647  247.2953  249.2728    10
   app$find_widget("num") 1674.4174 1743.8341 1744.8994 1746.5740 1748.1369 1778.7303    10
            w$get_value()  232.8772  238.9434  243.8246  242.8571  247.5394  257.8989    10
         w$set_value("1")  498.5309  507.5961  516.4700  510.0424  521.5700  557.1425    10
```

**Comment by gaborcsardi** [comment]
Thanks! This is OSX, huge difference, 10-20x faster than windows:

```r
❯ microbenchmark::microbenchmark(app$find_element("#num"), app$find_widget("num"), w$get_value(), w$set_value("1"), times = 10)
Unit: milliseconds
                     expr      min       lq     mean   median       uq       max neval cld
 app$find_element("#num") 12.55715 12.88035 16.40077 14.01072 17.14237  34.11687    10 a
   app$find_widget("num") 74.94444 76.04604 84.95487 81.79317 91.68355 107.12566    10   c
            w$get_value() 11.75901 12.26733 13.52015 12.66015 13.39283  19.40257    10 a
         w$set_value("1") 33.06083 36.75604 42.67280 39.13500 43.52828  76.50936    10  b
```

**Comment by daattali** [comment]
Damn. I might finally have a valid reason to switch my development to a
proper OS.

But the same patterns are seen - find_widget() 7x slower than
find_element(), seems a bit excessive (though I have no idea what's going
on in the code)

---
http://deanattali.com

**Comment by gaborcsardi** [comment]
@daattali I suspect that this is because `find_widget` does multiple phantom operations. But will need to measure, really.

**Comment by daattali** [comment]
Perhaps the code inside find_widget can try to be a bit smarter since we know it's so slow on windows by trying to minimize the number of phantom operations?

For example, the first few lines always do 3 find_element() calls https://github.com/MangoTheCat/shinytest/blob/8a380fa7207d16e347f922888e3a1db7c8984efe/R/shiny-mapping.R#L15-L23

Instead, can't we only do one find_element(), and then just see if that element has the `.shiny-bound-input` or `.shiny-bound-output` class? This could make already reduce the time by a lot

Similarly, maybe not all 4 checks [here](https://github.com/MangoTheCat/shinytest/blob/8a380fa7207d16e347f922888e3a1db7c8984efe/R/shiny-mapping.R#L26-L29) are necessary - if we know that el_input or el_output are NULL then we know to not check some of them, right? I'm not sure if these lines are slow though, maybe it won't matter at all.

**Comment by gaborcsardi** [comment]
Agreed. I didn't think it would be a performance issue, so I prefered to write it cleanly. 

But even a single `find_element` takes too long to my taste.

**Comment by daattali** [comment]
Yes, agree with the notion of not optimizing before you know it's a problem. And yes definitely 250ms is not ideal for windows users

**Comment by gaborcsardi** [comment]
Another measurement from a Windows 8 VM:

```r
> microbenchmark::microbenchmark(app$find_element("#num"), app$find_widget("num"), w$get_value(), w$set_value("1"), times = 10)
Unit: milliseconds
                     expr       min        lq      mean    median        uq       max neval
 app$find_element("#num")  215.8409  220.2198  221.7486  221.2050  225.8429  226.6271    10
   app$find_widget("num") 1300.5032 1314.3314 1338.2020 1324.0260 1360.5459 1408.3377    10
            w$get_value()  206.5789  216.0765  220.0099  220.8701  225.3121  227.6955    10
         w$set_value("1")  442.9732  449.2106  463.1710  461.8125  471.7664  490.3302    10
```

This basically reproduces @daattali 's values.

**Comment by gaborcsardi** [comment]
@daattali OK, I found the reason. DNS resolution takes forever for `localhost`. I am not sure why, but hey, windows is an OS with internet-phobia. After connecting to 127.0.0.1, my measurements:

```r
> microbenchmark::microbenchmark(app$find_element("#num"), app$find_widget("num"), w$get_value(), w$set_value("1"), times = 10)
Unit: milliseconds
                     expr       min        lq      mean    median        uq       max neval
 app$find_element("#num")  15.83361  17.45707  23.66043  20.04972  24.99756  52.59522    10
   app$find_widget("num") 100.52356 115.73125 144.87243 140.73713 161.68199 230.29386    10
            w$get_value()  15.76022  16.79659  27.39624  19.51916  39.34466  59.85411    10
         w$set_value("1")  50.08770  55.48717  65.67883  59.51811  75.60494  94.63087    10
```
which is almost as fast as OSX, and this was in a VM.

Committing a fix soon.

**Comment by gaborcsardi** [comment]
I believe that 34e4c8d8c310f11d3b25166c8eedf5a14c4bb0f6 fixes it. 

@daattali can you please try when you have time? I'll leave this issue open until you can confirm. Not urgent, no rush. :)

**Comment by daattali** [comment]
Huh, that's good to know, how'd you figure that out? Just try to replace the URL, or did you read about it somewhere?

I do see about a 10fold improvement, except for find_widget which is "only" 3x better. 

```
> microbenchmark::microbenchmark(app$find_element("#num"), app$find_widget("num"), w$get_value(), w$set_value("1"), times = 50)
Unit: milliseconds
                     expr       min        lq      mean    median        uq       max neval
 app$find_element("#num")  24.45292  28.09156  33.10312  30.74988  38.50017  49.98237    50
   app$find_widget("num") 448.28940 493.74794 507.07447 508.53321 519.46799 548.54480    50
            w$get_value()  23.72571  26.17566  30.29353  27.58500  35.57848  39.06867    50
         w$set_value("1")  68.70335  82.49989  91.34158  89.58362  96.54456 124.45615    50
```

I do think there can be great value in trying my [earlier suggestion](https://github.com/MangoTheCat/webdriver/issues/27#issuecomment-247567901) of making find_widget a bit smarter with very minimal code change

**Comment by gaborcsardi** [comment]
I was just lucky, I was reading over the code, and remembered that localhost is not defined on windows by default. The web is full with this issue, e.g. http://stackoverflow.com/questions/1416128/my-local-host-goes-so-slow-now-that-i-am-on-windows-7-and-asp-net-mvc

Yes, we can certainly refactor `find_widget` to minimize the number of WebDriver queries.

**Comment by gaborcsardi** [comment]
@daattali Btw. pls also try re-installing `shinytest`, I turned off the proxy, maybe that matters, too. Maybe not.

**Comment by daattali** [comment]
I reinstalled webdriver and shinytest before running previously

**Comment by gaborcsardi** [comment]
Here is my latest benchmark, after the recent "fixes":

```r
❯ microbenchmark::microbenchmark(app$find_element("#num"), app$find_widget("num"), w$get_value(), w$set_value("1"), times = 50)
Unit: milliseconds
                     expr       min        lq      mean    median        uq       max neval cld
 app$find_element("#num") 10.063606 10.370052 11.489246 10.546307 11.621988  16.03090    50  a
   app$find_widget("num") 57.132324 59.122871 66.262567 62.266675 70.246913 111.22127    50   b
            w$get_value()  8.208624  8.321911  8.809516  8.447059  8.811641  12.42366    50  a
         w$set_value("1")  8.404800  8.802872 10.171434  9.110066  9.907177  34.36437    50  a
```

This is already reasonable, and the app startup is taking the longest.

Note that `find_widget` is still kind of a mess, so cleaning that up will make things potentially even faster.

**Comment by daattali** [comment]
Haven't tested, but those numbers do look great

**Comment by gaborcsardi** [comment]
Rewritten `find_widget`: 

```r
Unit: milliseconds
                     expr       min        lq     mean    median       uq      max neval cld
 app$find_element("#num") 10.181136 10.819317 12.60258 11.588425 12.54882 42.21777    50  b
   app$find_widget("num") 19.291952 20.807235 22.08593 21.842526 22.51589 28.89054    50   c
            w$get_value()  8.430897  9.060242 10.65549  9.583603 10.52882 37.99533    50 a
         w$set_value("1")  8.397527  9.243961 10.37221  9.900995 10.88256 15.81617    50 a
```

It seems like one phantom call is about 10ms. The `find_widget` method has two calls now. I could reduce it to one, but I'll leave that for later....

**Comment by daattali** [comment]
This is good enough, great work.  Now enjoy your weekend
