### ISSUE TITLE
Should change default viewport size

### ISSUE THREAD

**Issue by wch** [MangoTheCat/webdriver#40]
The default viewport size for phantomjs is very narrow, at 400 pixels. This results in a layout like the one below:
![image](https://cloud.githubusercontent.com/assets/86978/19205401/d4144f24-8ca7-11e6-9382-f742bbce04b0.png)

Webshot uses a 992x744 viewport, and I think this would be a good setting here as well. The 992-pixel width is because that's Bootstrap's threshold for  a "medium" device like a computer desktop: http://getbootstrap.com/css/#grid-media-queries

I don't recall why I used 744 for the height in webshot. It does result in a 4:3 ratio, though, so that might be why.

**Comment by gaborcsardi** [comment]
Yes, I guess we can just call `app$set_window_size` it in the constructor of `shinyapp`.

**Comment by gaborcsardi** [comment]
Oh, wait, this is webdriver, I "fixed" this in shinytest....
https://github.com/MangoTheCat/shinytest/commit/a4f30f33b176d67b507561c3c0acd23d5858ec07

I'll move it over here....
